SET IDENTITY_INSERT CUSTOMER ON;

INSERT INTO CUSTOMER (ID) VALUES (1)

INSERT INTO CUSTOMER (ID)
SELECT MissingIDs.ID
from (
	SELECT DISTINCT INVOICE.CUSTOMER_ID as ID
	FROM INVOICE
	LEFT JOIN CUSTOMER ON INVOICE.CUSTOMER_ID = CUSTOMER.ID
	WHERE CUSTOMER.ID is Null
) as MissingIDs;

SET IDENTITY_INSERT CUSTOMER OFF;
